// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BestPracticeDocumentDataSlicesSlice =
  | AccordionSectionSlice
  | TextSectionSlice
  | HeroBannerSlice
  | TextSlice;

/**
 * Content for Best practice documents
 */
interface BestPracticeDocumentData {
  /**
   * Slice Zone field in *Best practice*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: best_practice.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BestPracticeDocumentDataSlicesSlice> /**
   * Meta Description field in *Best practice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: best_practice.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Best practice*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: best_practice.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Best practice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: best_practice.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Best practice document from Prismic
 *
 * - **API ID**: `best_practice`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BestPracticeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BestPracticeDocumentData>,
    "best_practice",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | TimelineSlice
  | TextSlice
  | TextSectionSlice
  | CheckListSlice
  | AccordionSectionSlice
  | NewsListSlice
  | FormSectionSlice
  | HeroBannerSlice
  | FeaturedPartnersSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type HomepageDocumentDataSlicesSlice =
  | HeroBannerSlice
  | FeaturedPartnersSlice
  | AccordionSectionSlice
  | FormSectionSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NavigationDocumentDataSlices1Slice = MenuItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Logo field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never> /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices1[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<NavigationDocumentDataSlices1Slice> /**
   * Search bar placeholder field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.search_bar_placeholder
   * - **Tab**: Search
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  search_bar_placeholder: prismic.KeyTextField;

  /**
   * Search result page title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.search_result_page_title
   * - **Tab**: Search
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  search_result_page_title: prismic.KeyTextField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FeaturesSlice
  | CallToActionSlice
  | PartnershipTiersSlice
  | TextSectionSlice
  | TimelineSlice
  | CheckListSlice
  | TextSlice
  | HeroBannerSlice
  | NewsListSlice
  | FormSectionSlice
  | FeaturedPartnersSlice
  | AccordionSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Partnership Tier → Tier features*
 */
export interface PartnershipTierDocumentDataTierFeaturesItem {
  /**
   * Feature Description field in *Partnership Tier → Tier features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tier.tier_features[].feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField;

  /**
   * Feature Icon field in *Partnership Tier → Tier features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tier.tier_features[].feature_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_icon: prismic.ImageField<never>;
}

/**
 * Content for Partnership Tier documents
 */
interface PartnershipTierDocumentData {
  /**
   * Tier name field in *Partnership Tier*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tier.tier_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tier_name: prismic.TitleField;

  /**
   * Tier description field in *Partnership Tier*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tier.tier_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tier_description: prismic.RichTextField;

  /**
   * Tier image field in *Partnership Tier*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tier.tier_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tier_image: prismic.ImageField<never>;

  /**
   * Is Featured tier field in *Partnership Tier*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: partnership_tier.is_featured_tier
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_featured_tier: prismic.BooleanField;

  /**
   * Tier features field in *Partnership Tier*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tier.tier_features[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tier_features: prismic.GroupField<
    Simplify<PartnershipTierDocumentDataTierFeaturesItem>
  >;
}

/**
 * Partnership Tier document from Prismic
 *
 * - **API ID**: `partnership_tier`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartnershipTierDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PartnershipTierDocumentData>,
    "partnership_tier",
    Lang
  >;

type ReviewDocumentDataSlicesSlice =
  | TimelineSlice
  | TextSlice
  | TextSectionSlice
  | CheckListSlice
  | HeroBannerSlice
  | AccordionSectionSlice;

/**
 * Content for Review documents
 */
interface ReviewDocumentData {
  /**
   * Slice Zone field in *Review*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: review.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReviewDocumentDataSlicesSlice> /**
   * Meta Description field in *Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: review.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Review*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: review.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: review.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Review document from Prismic
 *
 * - **API ID**: `review`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ReviewDocumentData>, "review", Lang>;

type ReviewsDocumentDataSlicesSlice =
  | FormSectionSlice
  | AccordionSectionSlice
  | HeroBannerSlice
  | TextSlice;

/**
 * Content for Reviews documents
 */
interface ReviewsDocumentData {
  /**
   * Slice Zone field in *Reviews*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReviewsDocumentDataSlicesSlice> /**
   * Meta Description field in *Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: reviews.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: reviews.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Reviews document from Prismic
 *
 * - **API ID**: `reviews`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReviewsDocumentData>,
    "reviews",
    Lang
  >;

/**
 * Item in *Reviews checklist → Criteria*
 */
export interface ReviewsChecklistDocumentDataCriteriaItem {
  /**
   * Topic field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_checklist.criteria[].topic
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  topic: prismic.SelectField<
    | "Slices and types"
    | "Queries"
    | "Templating into React/Vue"
    | "Routing"
    | "Content relationship"
    | "Assets"
    | "Dev experience"
    | "Editor experience"
  >;

  /**
   * Name field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_checklist.criteria[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Comment Next field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Comment for Next apps
   * - **API ID Path**: reviews_checklist.criteria[].comment_next
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  comment_next: prismic.RichTextField;

  /**
   * Comment Nuxt field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Comment for Nuxt apps
   * - **API ID Path**: reviews_checklist.criteria[].comment_nuxt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  comment_nuxt: prismic.RichTextField;

  /**
   * Comment Sveltkit field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Comment for SveltKit apps
   * - **API ID Path**: reviews_checklist.criteria[].comment_sveltkit
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  comment_sveltkit: prismic.RichTextField;

  /**
   * Priority field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Criteria priority
   * - **API ID Path**: reviews_checklist.criteria[].priority
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  priority: prismic.SelectField<"High" | "Medium" | "Low">;

  /**
   * Is Slice library field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: reviews_checklist.criteria[].is_slice_library
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_slice_library: prismic.BooleanField;

  /**
   * Is Full Project field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: reviews_checklist.criteria[].is_full_project
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_full_project: prismic.BooleanField;

  /**
   * Review helper field in *Reviews checklist → Criteria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Helper for SE team
   * - **API ID Path**: reviews_checklist.criteria[].review_helper
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  review_helper: prismic.RichTextField;
}

/**
 * Content for Reviews checklist documents
 */
interface ReviewsChecklistDocumentData {
  /**
   * Criteria field in *Reviews checklist*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_checklist.criteria[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  criteria: prismic.GroupField<
    Simplify<ReviewsChecklistDocumentDataCriteriaItem>
  >;
}

/**
 * Reviews checklist document from Prismic
 *
 * - **API ID**: `reviews_checklist`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewsChecklistDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReviewsChecklistDocumentData>,
    "reviews_checklist",
    Lang
  >;

type UseCaseDocumentDataSlicesSlice =
  | NewsListSlice
  | TextSectionSlice
  | AccordionSectionSlice
  | HeroBannerSlice
  | TextSlice
  | FormSectionSlice;

/**
 * Content for Use case documents
 */
interface UseCaseDocumentData {
  /**
   * Slice Zone field in *Use case*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: use_case.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UseCaseDocumentDataSlicesSlice> /**
   * Meta Description field in *Use case*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: use_case.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Use case*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: use_case.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Use case*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: use_case.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Use case document from Prismic
 *
 * - **API ID**: `use_case`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UseCaseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<UseCaseDocumentData>,
    "use_case",
    Lang
  >;

export type AllDocumentTypes =
  | BestPracticeDocument
  | HomeDocument
  | HomepageDocument
  | NavigationDocument
  | PageDocument
  | PartnershipTierDocument
  | ReviewDocument
  | ReviewsDocument
  | ReviewsChecklistDocument
  | UseCaseDocument;

/**
 * Primary content in *AccordionSection → Primary*
 */
export interface AccordionSectionSliceWithImagePrimary {
  /**
   * Eyebrow field in *AccordionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Section Title field in *AccordionSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Description field in *AccordionSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *AccordionSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *AccordionSection → Items*
 */
export interface AccordionSectionSliceWithImageItem {
  /**
   * Accordion Title field in *AccordionSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Type the accordion title here...
   * - **API ID Path**: accordion_section.items[].accordion_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordion_title: prismic.KeyTextField;

  /**
   * Accordion Content field in *AccordionSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Type the accordion content here...
   * - **API ID Path**: accordion_section.items[].accordion_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accordion_content: prismic.RichTextField;
}

/**
 * With image variation for AccordionSection Slice
 *
 * - **API ID**: `withImage`
 * - **Description**: Default variation with multiple collapsible items.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSectionSliceWithImage = prismic.SharedSliceVariation<
  "withImage",
  Simplify<AccordionSectionSliceWithImagePrimary>,
  Simplify<AccordionSectionSliceWithImageItem>
>;

/**
 * Primary content in *AccordionSection → Primary*
 */
export interface AccordionSectionSliceTwoColumnsPrimary {
  /**
   * Eyebrow field in *AccordionSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Section Title field in *AccordionSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Description field in *AccordionSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AccordionSection → Items*
 */
export interface AccordionSectionSliceTwoColumnsItem {
  /**
   * Accordion Title field in *AccordionSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Type the accordion title here...
   * - **API ID Path**: accordion_section.items[].accordion_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordion_title: prismic.KeyTextField;

  /**
   * Accordion Content field in *AccordionSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Type the accordion content here...
   * - **API ID Path**: accordion_section.items[].accordion_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accordion_content: prismic.RichTextField;
}

/**
 * Two Columns variation for AccordionSection Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Default variation with multiple collapsible items.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSectionSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<AccordionSectionSliceTwoColumnsPrimary>,
  Simplify<AccordionSectionSliceTwoColumnsItem>
>;

/**
 * Primary content in *AccordionSection → Primary*
 */
export interface AccordionSectionSliceCenteredPrimary {
  /**
   * Section Title field in *AccordionSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;
}

/**
 * Primary content in *AccordionSection → Items*
 */
export interface AccordionSectionSliceCenteredItem {
  /**
   * Accordion Title field in *AccordionSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Type the accordion title here...
   * - **API ID Path**: accordion_section.items[].accordion_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordion_title: prismic.KeyTextField;

  /**
   * Accordion Content field in *AccordionSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Type the accordion content here...
   * - **API ID Path**: accordion_section.items[].accordion_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accordion_content: prismic.RichTextField;
}

/**
 * Centered variation for AccordionSection Slice
 *
 * - **API ID**: `centered`
 * - **Description**: Default variation with multiple collapsible items.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSectionSliceCentered = prismic.SharedSliceVariation<
  "centered",
  Simplify<AccordionSectionSliceCenteredPrimary>,
  Simplify<AccordionSectionSliceCenteredItem>
>;

/**
 * Slice variation for *AccordionSection*
 */
type AccordionSectionSliceVariation =
  | AccordionSectionSliceWithImage
  | AccordionSectionSliceTwoColumns
  | AccordionSectionSliceCentered;

/**
 * AccordionSection Shared Slice
 *
 * - **API ID**: `accordion_section`
 * - **Description**: A structured component suitable for presenting more detailed and linked content, such as FAQs or review checklist criteria. The accordion format allows for organized information display, ensuring a clean and user-friendly experience.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSectionSlice = prismic.SharedSlice<
  "accordion_section",
  AccordionSectionSliceVariation
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Title field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Cta Label field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Cta Link field in *CallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Cta Type field in *CallToAction → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Primary, secondary or link
   * - **Default Value**: primary
   * - **API ID Path**: call_to_action.primary.cta_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  cta_type: prismic.SelectField<"primary" | "secondary" | "link", "filled">;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceTwoColumnsPrimary {
  /**
   * Title field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceTwoColumnsItem {
  /**
   * Cta Label field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Cta Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Cta Type field in *CallToAction → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: call_to_action.items[].cta_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  cta_type: prismic.SelectField<"primary" | "secondary" | "link", "filled">;
}

/**
 * Two Columns variation for CallToAction Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<CallToActionSliceTwoColumnsPrimary>,
  Simplify<CallToActionSliceTwoColumnsItem>
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceTwoColumns;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *CheckList → Primary*
 */
export interface CheckListSliceDefaultVariationPrimary {
  /**
   * Section Title field in *CheckList → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: check_list.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;
}

/**
 * Primary content in *CheckList → Items*
 */
export interface CheckListSliceDefaultVariationItem {
  /**
   * Item Title field in *CheckList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: check_list.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item_title: prismic.RichTextField;

  /**
   * Item Description field in *CheckList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: check_list.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  item_description: prismic.RichTextField;

  /**
   * Item Image field in *CheckList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: check_list.items[].item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  item_image: prismic.ImageField<never>;

  /**
   * Item Visibility field in *CheckList → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: check_list.items[].item_visibility
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  item_visibility: prismic.BooleanField;
}

/**
 * Default Variation variation for CheckList Slice
 *
 * - **API ID**: `default_variation`
 * - **Description**: Default variation where each item in the checklist contains a title, description, and image, with a toggle to hide description and image.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CheckListSliceDefaultVariation = prismic.SharedSliceVariation<
  "default_variation",
  Simplify<CheckListSliceDefaultVariationPrimary>,
  Simplify<CheckListSliceDefaultVariationItem>
>;

/**
 * Slice variation for *CheckList*
 */
type CheckListSliceVariation = CheckListSliceDefaultVariation;

/**
 * CheckList Shared Slice
 *
 * - **API ID**: `check_list`
 * - **Description**: The Check List component displays the list of items to cover to become certified. Each item has a title, a description and an image. In each item it is possible to hide the description and image with a toggle.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CheckListSlice = prismic.SharedSlice<
  "check_list",
  CheckListSliceVariation
>;

/**
 * Primary content in *FeaturedPartners → Primary*
 */
export interface FeaturedPartnersSliceDefaultVariationPrimary {
  /**
   * Section Title field in *FeaturedPartners → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_partners.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Section Description field in *FeaturedPartners → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_partners.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;

  /**
   * See All Button Label field in *FeaturedPartners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_partners.primary.see_all_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  see_all_button_label: prismic.KeyTextField;

  /**
   * See All Button Link field in *FeaturedPartners → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to all partners
   * - **API ID Path**: featured_partners.primary.see_all_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  see_all_button_link: prismic.LinkField;
}

/**
 * Primary content in *FeaturedPartners → Items*
 */
export interface FeaturedPartnersSliceDefaultVariationItem {
  /**
   * Partner Link field in *FeaturedPartners → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL to partner's page
   * - **API ID Path**: featured_partners.items[].partner_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  partner_link: prismic.LinkField;

  /**
   * Partner Logo field in *FeaturedPartners → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_partners.items[].partner_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  partner_logo: prismic.ImageField<never>;
}

/**
 * Default Variation variation for FeaturedPartners Slice
 *
 * - **API ID**: `default_variation`
 * - **Description**: A standard layout for displaying featured partner logos in a visually appealing grid.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedPartnersSliceDefaultVariation =
  prismic.SharedSliceVariation<
    "default_variation",
    Simplify<FeaturedPartnersSliceDefaultVariationPrimary>,
    Simplify<FeaturedPartnersSliceDefaultVariationItem>
  >;

/**
 * Slice variation for *FeaturedPartners*
 */
type FeaturedPartnersSliceVariation = FeaturedPartnersSliceDefaultVariation;

/**
 * FeaturedPartners Shared Slice
 *
 * - **API ID**: `featured_partners`
 * - **Description**: A showcase of partner logos, arranged in a grid layout, to highlight and link to featured partners.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedPartnersSlice = prismic.SharedSlice<
  "featured_partners",
  FeaturedPartnersSliceVariation
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Eyebrow field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Feature name field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.feature_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_name: prismic.RichTextField;

  /**
   * Feature Description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceWithImagePrimary {
  /**
   * Eyebrow field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Feature name field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.feature_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_name: prismic.RichTextField;

  /**
   * Feature Description field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.feature_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_description: prismic.RichTextField;

  /**
   * Image field in *Features → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * With Image variation for Features Slice
 *
 * - **API ID**: `withImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceWithImage = prismic.SharedSliceVariation<
  "withImage",
  Simplify<FeaturesSliceWithImagePrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault | FeaturesSliceWithImage;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *FormSection → Primary*
 */
export interface FormSectionSliceDefaultPrimary {
  /**
   * Section Title field in *FormSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the section title here
   * - **API ID Path**: form_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Section Description field in *FormSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the section description here
   * - **API ID Path**: form_section.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;

  /**
   * Submit Button Text field in *FormSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the text for the submit button
   * - **API ID Path**: form_section.primary.submit_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submit_button_text: prismic.KeyTextField;
}

/**
 * Primary content in *FormSection → Items*
 */
export interface FormSectionSliceDefaultItem {
  /**
   * Input Label field in *FormSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the label for the input field
   * - **API ID Path**: form_section.items[].input_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_label: prismic.KeyTextField;

  /**
   * Input Type field in *FormSection → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the type of the input field
   * - **API ID Path**: form_section.items[].input_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  input_type: prismic.SelectField<"text" | "email" | "textarea">;

  /**
   * Input Name field in *FormSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the name attribute for the input field
   * - **API ID Path**: form_section.items[].input_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_name: prismic.KeyTextField;

  /**
   * Is Input Required? field in *FormSection → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: form_section.items[].input_required
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  input_required: prismic.BooleanField;
}

/**
 * Default Variation variation for FormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: The default layout of the Form slice which includes text inputs for name, email, and a message area.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSectionSliceDefaultPrimary>,
  Simplify<FormSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FormSection*
 */
type FormSectionSliceVariation = FormSectionSliceDefault;

/**
 * FormSection Shared Slice
 *
 * - **API ID**: `form_section`
 * - **Description**: An interactive component for agencies to contact an executive, including fields for name, email, and message, to facilitate seamless communication and streamline the agency qualification process.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSectionSlice = prismic.SharedSlice<
  "form_section",
  FormSectionSliceVariation
>;

/**
 * Primary content in *HeroBanner → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Title field in *HeroBanner → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the banner title here...
   * - **API ID Path**: hero_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the description here...
   * - **API ID Path**: hero_banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the button text here...
   * - **API ID Path**: hero_banner.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *HeroBanner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL or link to the document
   * - **API ID Path**: hero_banner.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default Variation variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with a title, a description, and a button
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: The section is the Hero Banner, that displays in the center a title, a description, and a button.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *MenuItem → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Label field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MenuItem → Primary*
 */
export interface MenuItemSliceWithSubMenuPrimary {
  /**
   * Label field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *MenuItem → Items*
 */
export interface MenuItemSliceWithSubMenuItem {
  /**
   * Sub menu item label field in *MenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].sub_menu_item_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_menu_item_label: prismic.KeyTextField;

  /**
   * Sub menu item link field in *MenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].sub_menu_item_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_menu_item_link: prismic.LinkField;
}

/**
 * With sub menu variation for MenuItem Slice
 *
 * - **API ID**: `withSubMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceWithSubMenu = prismic.SharedSliceVariation<
  "withSubMenu",
  Simplify<MenuItemSliceWithSubMenuPrimary>,
  Simplify<MenuItemSliceWithSubMenuItem>
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault | MenuItemSliceWithSubMenu;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Primary content in *NewsList → Primary*
 */
export interface NewsListSliceDefaultPrimary {
  /**
   * Section Title field in *NewsList → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the section title for the news list here...
   * - **API ID Path**: news_list.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;
}

/**
 * Primary content in *NewsList → Items*
 */
export interface NewsListSliceDefaultItem {
  /**
   * News Image field in *NewsList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_list.items[].news_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  news_image: prismic.ImageField<never>;

  /**
   * News Title field in *NewsList → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Insert news title...
   * - **API ID Path**: news_list.items[].news_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  news_title: prismic.TitleField;

  /**
   * News Description field in *NewsList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write a short description for this news item...
   * - **API ID Path**: news_list.items[].news_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  news_description: prismic.RichTextField;

  /**
   * News Link field in *NewsList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Paste the URL or link to the full article...
   * - **API ID Path**: news_list.items[].news_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  news_link: prismic.LinkField;

  /**
   * Link Label field in *NewsList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter link text, such as 'Read more'...
   * - **API ID Path**: news_list.items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Default Variation variation for NewsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with a grid of news items, including images and descriptions for each piece of news.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsListSliceDefaultPrimary>,
  Simplify<NewsListSliceDefaultItem>
>;

/**
 * Slice variation for *NewsList*
 */
type NewsListSliceVariation = NewsListSliceDefault;

/**
 * NewsList Shared Slice
 *
 * - **API ID**: `news_list`
 * - **Description**: The News List is a curated list of linked news and announcements. This component provides a concise overview of the latest updates and developments within the Prismic ecosystem. Each news item is linked, allowing visitors to explore further details and stay informed about important announcements. A detailed description of the slice design includes a visually organized list with clickable news items, ensuring a seamless navigation experience. The purpose of the slice is to keep visitors informed about the latest news and updates.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsListSlice = prismic.SharedSlice<
  "news_list",
  NewsListSliceVariation
>;

/**
 * Primary content in *PartnershipTiers → Primary*
 */
export interface PartnershipTiersSliceHorizontalCardsPrimary {
  /**
   * TItle field in *PartnershipTiers → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tiers.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *PartnershipTiers → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tiers.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *PartnershipTiers → Items*
 */
export interface PartnershipTiersSliceHorizontalCardsItem {
  /**
   * Tier field in *PartnershipTiers → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tiers.items[].tier
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tier: prismic.ContentRelationshipField<"partnership_tier">;
}

/**
 * Horizontal Cards variation for PartnershipTiers Slice
 *
 * - **API ID**: `horizontalCards`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnershipTiersSliceHorizontalCards = prismic.SharedSliceVariation<
  "horizontalCards",
  Simplify<PartnershipTiersSliceHorizontalCardsPrimary>,
  Simplify<PartnershipTiersSliceHorizontalCardsItem>
>;

/**
 * Primary content in *PartnershipTiers → Primary*
 */
export interface PartnershipTiersSliceFullWidthCardsPrimary {
  /**
   * TItle field in *PartnershipTiers → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tiers.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *PartnershipTiers → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tiers.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *PartnershipTiers → Items*
 */
export interface PartnershipTiersSliceFullWidthCardsItem {
  /**
   * Tier field in *PartnershipTiers → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_tiers.items[].tier
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tier: prismic.ContentRelationshipField<"partnership_tier">;
}

/**
 * Full Width Cards variation for PartnershipTiers Slice
 *
 * - **API ID**: `fullWidthCards`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnershipTiersSliceFullWidthCards = prismic.SharedSliceVariation<
  "fullWidthCards",
  Simplify<PartnershipTiersSliceFullWidthCardsPrimary>,
  Simplify<PartnershipTiersSliceFullWidthCardsItem>
>;

/**
 * Slice variation for *PartnershipTiers*
 */
type PartnershipTiersSliceVariation =
  | PartnershipTiersSliceHorizontalCards
  | PartnershipTiersSliceFullWidthCards;

/**
 * PartnershipTiers Shared Slice
 *
 * - **API ID**: `partnership_tiers`
 * - **Description**: PartnershipTiers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnershipTiersSlice = prismic.SharedSlice<
  "partnership_tiers",
  PartnershipTiersSliceVariation
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceSinglePrimary {
  /**
   * Company logo field in *Testimonials → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.company_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Quote field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Author name field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author role field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.author_role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_role: prismic.KeyTextField;

  /**
   * Author image field in *Testimonials → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author company field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.author_company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_company: prismic.KeyTextField;
}

/**
 * Single variation for Testimonials Slice
 *
 * - **API ID**: `single`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceSingle = prismic.SharedSliceVariation<
  "single",
  Simplify<TestimonialsSliceSinglePrimary>,
  never
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceSliderPrimary {
  /**
   * Title field in *Testimonials → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceSliderItem {
  /**
   * Quote field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Author name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author role field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_role: prismic.KeyTextField;

  /**
   * Author image field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author company field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_company: prismic.KeyTextField;
}

/**
 * Slider variation for Testimonials Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceSlider = prismic.SharedSliceVariation<
  "slider",
  Simplify<TestimonialsSliceSliderPrimary>,
  Simplify<TestimonialsSliceSliderItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation =
  | TestimonialsSliceSingle
  | TestimonialsSliceSlider;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text Section field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text_section
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_section: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextSection → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
  /**
   * Content field in *TextSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Type your engaging rich content here...
   * - **API ID Path**: text_section.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default Variation variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with full rich text formatting support for engaging content.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextSection → Primary*
 */
export interface TextSectionSliceTwoColumnPrimary {
  /**
   * Content field in *TextSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Type your engaging rich content here...
   * - **API ID Path**: text_section.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Two Column variation for TextSection Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Default variation with full rich text formatting support for engaging content.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSliceTwoColumn = prismic.SharedSliceVariation<
  "twoColumn",
  Simplify<TextSectionSliceTwoColumnPrimary>,
  never
>;

/**
 * Slice variation for *TextSection*
 */
type TextSectionSliceVariation =
  | TextSectionSliceDefault
  | TextSectionSliceTwoColumn;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: A rich and engaging text section for long form content, with advanced styling for various formatting options including lists, headings, bold, italic, and links.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSlice = prismic.SharedSlice<
  "text_section",
  TextSectionSliceVariation
>;

/**
 * Primary content in *Timeline → Primary*
 */
export interface TimelineSliceAlternatedWithImagePrimary {
  /**
   * Section Title field in *Timeline → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the title of the timeline here...
   * - **API ID Path**: timeline.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Section Description field in *Timeline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a short description of the timeline here...
   * - **API ID Path**: timeline.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;
}

/**
 * Primary content in *Timeline → Items*
 */
export interface TimelineSliceAlternatedWithImageItem {
  /**
   * Step Number field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01, 02, etc.
   * - **API ID Path**: timeline.items[].step_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_number: prismic.KeyTextField;

  /**
   * Step Title field in *Timeline → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].step_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_title: prismic.TitleField;

  /**
   * Step Description field in *Timeline → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].step_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_description: prismic.RichTextField;

  /**
   * Link label field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Read more link label
   * - **API ID Path**: timeline.items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Read More Link field in *Timeline → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add a link for more details...
   * - **API ID Path**: timeline.items[].read_more_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  read_more_link: prismic.LinkField;

  /**
   * Milestone Image field in *Timeline → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].milestone_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  milestone_image: prismic.ImageField<never>;
}

/**
 * Alternated With Image variation for Timeline Slice
 *
 * - **API ID**: `alternatedWithImage`
 * - **Description**: The standard layout of the timeline component, showcasing the steps involved in the partnership process.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSliceAlternatedWithImage = prismic.SharedSliceVariation<
  "alternatedWithImage",
  Simplify<TimelineSliceAlternatedWithImagePrimary>,
  Simplify<TimelineSliceAlternatedWithImageItem>
>;

/**
 * Primary content in *Timeline → Primary*
 */
export interface TimelineSliceLinearPrimary {
  /**
   * Section Title field in *Timeline → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the title of the timeline here...
   * - **API ID Path**: timeline.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Section Description field in *Timeline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a short description of the timeline here...
   * - **API ID Path**: timeline.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;
}

/**
 * Primary content in *Timeline → Items*
 */
export interface TimelineSliceLinearItem {
  /**
   * Step Number field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01, 02, etc.
   * - **API ID Path**: timeline.items[].step_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_number: prismic.KeyTextField;

  /**
   * Step Title field in *Timeline → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].step_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_title: prismic.TitleField;

  /**
   * Step Description field in *Timeline → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].step_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_description: prismic.RichTextField;

  /**
   * Link label field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Read more link label
   * - **API ID Path**: timeline.items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Read More Link field in *Timeline → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add a link for more details...
   * - **API ID Path**: timeline.items[].read_more_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  read_more_link: prismic.LinkField;
}

/**
 * Linear variation for Timeline Slice
 *
 * - **API ID**: `linear`
 * - **Description**: The standard layout of the timeline component, showcasing the steps involved in the partnership process.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSliceLinear = prismic.SharedSliceVariation<
  "linear",
  Simplify<TimelineSliceLinearPrimary>,
  Simplify<TimelineSliceLinearItem>
>;

/**
 * Primary content in *Timeline → Primary*
 */
export interface TimelineSliceGridPrimary {
  /**
   * Section Title field in *Timeline → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Enter the title of the timeline here...
   * - **API ID Path**: timeline.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Section Description field in *Timeline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a short description of the timeline here...
   * - **API ID Path**: timeline.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;
}

/**
 * Primary content in *Timeline → Items*
 */
export interface TimelineSliceGridItem {
  /**
   * Step Number field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01, 02, etc.
   * - **API ID Path**: timeline.items[].step_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_number: prismic.KeyTextField;

  /**
   * Step Title field in *Timeline → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].step_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_title: prismic.TitleField;

  /**
   * Step Description field in *Timeline → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.items[].step_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_description: prismic.RichTextField;

  /**
   * Link label field in *Timeline → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Read more link label
   * - **API ID Path**: timeline.items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Read More Link field in *Timeline → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add a link for more details...
   * - **API ID Path**: timeline.items[].read_more_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  read_more_link: prismic.LinkField;
}

/**
 * Grid variation for Timeline Slice
 *
 * - **API ID**: `grid`
 * - **Description**: The standard layout of the timeline component, showcasing the steps involved in the partnership process.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSliceGrid = prismic.SharedSliceVariation<
  "grid",
  Simplify<TimelineSliceGridPrimary>,
  Simplify<TimelineSliceGridItem>
>;

/**
 * Slice variation for *Timeline*
 */
type TimelineSliceVariation =
  | TimelineSliceAlternatedWithImage
  | TimelineSliceLinear
  | TimelineSliceGrid;

/**
 * Timeline Shared Slice
 *
 * - **API ID**: `timeline`
 * - **Description**: The Timeline component displays a chronological series of events or steps along a vertical line.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSlice = prismic.SharedSlice<
  "timeline",
  TimelineSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BestPracticeDocument,
      BestPracticeDocumentData,
      BestPracticeDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlices1Slice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PartnershipTierDocument,
      PartnershipTierDocumentData,
      PartnershipTierDocumentDataTierFeaturesItem,
      ReviewDocument,
      ReviewDocumentData,
      ReviewDocumentDataSlicesSlice,
      ReviewsDocument,
      ReviewsDocumentData,
      ReviewsDocumentDataSlicesSlice,
      ReviewsChecklistDocument,
      ReviewsChecklistDocumentData,
      ReviewsChecklistDocumentDataCriteriaItem,
      UseCaseDocument,
      UseCaseDocumentData,
      UseCaseDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionSectionSlice,
      AccordionSectionSliceWithImagePrimary,
      AccordionSectionSliceWithImageItem,
      AccordionSectionSliceTwoColumnsPrimary,
      AccordionSectionSliceTwoColumnsItem,
      AccordionSectionSliceCenteredPrimary,
      AccordionSectionSliceCenteredItem,
      AccordionSectionSliceVariation,
      AccordionSectionSliceWithImage,
      AccordionSectionSliceTwoColumns,
      AccordionSectionSliceCentered,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceTwoColumnsPrimary,
      CallToActionSliceTwoColumnsItem,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceTwoColumns,
      CheckListSlice,
      CheckListSliceDefaultVariationPrimary,
      CheckListSliceDefaultVariationItem,
      CheckListSliceVariation,
      CheckListSliceDefaultVariation,
      FeaturedPartnersSlice,
      FeaturedPartnersSliceDefaultVariationPrimary,
      FeaturedPartnersSliceDefaultVariationItem,
      FeaturedPartnersSliceVariation,
      FeaturedPartnersSliceDefaultVariation,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceWithImagePrimary,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FeaturesSliceWithImage,
      FormSectionSlice,
      FormSectionSliceDefaultPrimary,
      FormSectionSliceDefaultItem,
      FormSectionSliceVariation,
      FormSectionSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceWithSubMenuPrimary,
      MenuItemSliceWithSubMenuItem,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MenuItemSliceWithSubMenu,
      NewsListSlice,
      NewsListSliceDefaultPrimary,
      NewsListSliceDefaultItem,
      NewsListSliceVariation,
      NewsListSliceDefault,
      PartnershipTiersSlice,
      PartnershipTiersSliceHorizontalCardsPrimary,
      PartnershipTiersSliceHorizontalCardsItem,
      PartnershipTiersSliceFullWidthCardsPrimary,
      PartnershipTiersSliceFullWidthCardsItem,
      PartnershipTiersSliceVariation,
      PartnershipTiersSliceHorizontalCards,
      PartnershipTiersSliceFullWidthCards,
      TestimonialsSlice,
      TestimonialsSliceSinglePrimary,
      TestimonialsSliceSliderPrimary,
      TestimonialsSliceSliderItem,
      TestimonialsSliceVariation,
      TestimonialsSliceSingle,
      TestimonialsSliceSlider,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSectionSlice,
      TextSectionSliceDefaultPrimary,
      TextSectionSliceTwoColumnPrimary,
      TextSectionSliceVariation,
      TextSectionSliceDefault,
      TextSectionSliceTwoColumn,
      TimelineSlice,
      TimelineSliceAlternatedWithImagePrimary,
      TimelineSliceAlternatedWithImageItem,
      TimelineSliceLinearPrimary,
      TimelineSliceLinearItem,
      TimelineSliceGridPrimary,
      TimelineSliceGridItem,
      TimelineSliceVariation,
      TimelineSliceAlternatedWithImage,
      TimelineSliceLinear,
      TimelineSliceGrid,
    };
  }
}
