// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion_section: dynamic(() => import("./Accordion")),
  call_to_action: dynamic(() => import("./CallToAction")),
  featured_partners: dynamic(() => import("./FeaturedPartners")),
  features: dynamic(() => import("./Features")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  partnership_tiers: dynamic(() => import("./PartnershipTiers")),
  testimonials: dynamic(() => import("./Testimonials")),
  timeline: dynamic(() => import("./Timeline")),
};
