// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articles: dynamic(() => import("./Articles")),
  project: dynamic(() => import("./Project")),
  text: dynamic(() => import("./Text")),
};
