// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  intro_slide: dynamic(() => import("./IntroSlide")),
  slide: dynamic(() => import("./Slide")),
  slider: dynamic(() => import("./Slider")),
  video_slide: dynamic(() => import("./VideoSlide")),
};
